name: My first Workflow 

on : push


jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v5

        - name: Welcome message and Read 
          run: |
            echo "My first Github Actions Job"
            ls -ltr
            cat README.md

        - name: Generate ASCII artwork
          run: cowsay -f dragon "Hello from GitHub Actions" > dragon.txt
