name: generating ASCII
on: push 

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v5

        - name: Install Cowsay Program 
          run: sudo apt-get install cowsay -y 

        - name: Execute Cowsay Program 
          run: cowsay -f bunny "Abhishek loves you my Bunny my BUBU my Vaishu! ðŸ‡ðŸ’–" >> cuddle.txt

        - name: Test file exists 
          run: grep -i "cuddle" cuddle.txt

        - name: Read file
          run: cat cuddle.txt

        - name: Checkout Repo files
          run: ls